### PR TITLE
Gotta pass the public key.

### PR DESCRIPTION
**Pull request by darron**
If you don't it just exits status 1 and doesn't give you any help info.

Not a big deal - just thought I'd note.

### CODE REVIEW

**Comment by titanous** [comment]
Hmm, flynn-cli [is supposed to](https://github.com/flynn/flynn-cli/blob/981c5104a45551716a0e6f5ba31110ec3264628f/keys.go#L117) do this automatically after checking ssh-agent. Can you tell me what the output and exit code of `ssh-add -L` is?

**Comment by titanous** [comment]
Oh, it might be because it's a dsa key, I'll add a fallback.

**Comment by darron** [comment]
I also didn't have any identities in ssh-agent at the moment - might also
be related.

**Comment by titanous** [comment]
Okay, that makes sense. The fallback if ssh-agent is empty is to go for `~/.ssh/id_rsa.pub`, and it doesn't look for `id_dsa.pub`. I will add to flynn-cli and test.

**Comment by ianneub** [comment]
I also had the exit status 1 error until I specified `~/.ssh/id_rsa.pub`. Output from `ssh-add -L` is:

```
The agent has no identities.
```

It exited with status `1`.

Edit: I'm on OS X 10.9.2

**Comment by titanous** [comment]
@ianneub Thanks, it's very likely that flynn-cli is not moving on to trying the path directly when ssh-add fails. I'll change it to ignore errors.

**Comment by titanous** [comment]
This issue should be fixed, run `flynn update` to get the latest version.

**Pull request closed without merging**
